services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=shiftrx
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    container_name: app
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - API_PORT=3001
      - DATABASE_URL=postgresql://postgres:1234@db:5432/shiftrx?schema=public
      - JWT_SECRET=SECRET123
      - JWT_REFRESH_SECRET=ANOTHER_SECRET123
    volumes:
      - ./src:/app/src
      - /app/node_modules
    ports:
      - '3001:3001'

  next:
    depends_on:
      app:
        condition: service_started
    build:
      context: ./next
      dockerfile: Dockerfile
    volumes:
      - ./next:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'

volumes:
  postgres_data:
  app_node-modules:
