services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=shiftrx
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    container_name: app
    build:
      context: .
    depends_on:
      db:
        condition: service_started
    environment:
      - API_PORT=3000
      - DATABASE_URL=postgresql://postgres:1234@db:5432/shiftrx?schema=public
    ports:
      - '3000:3000'

volumes:
  postgres_data:
  app_node-modules:
